version: '3'

services:
    php:
        build: ./php
        volumes:
            - ./src:/var/www
            - ./php/php.ini:/usr/local/etc/php/php.ini

    nginx:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/log:/var/log/nginx
        depends_on:
            - php

    postgres:
        image: postgres:latest
        volumes:
            - ./postgres:/var/lib/postgresql
        environment:
            POSTGRES_DB: myproject
            POSTGRES_USER: myproject
            POSTGRES_PASSWORD: password

    pgadmin:
        image: dpage/pgadmin4
        volumes:
            - ./pgadmin:/var/lib/pgadmin/storage
        ports:
            - "8080:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: myproject
            PGADMIN_DEFAULT_PASSWORD: myproject

    mysql:
        image: mysql:5.7
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: myproject
            MYSQL_USER: myproject
            MYSQL_PASSWORD: password

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80"
        volumes:
            - ./phpmyadmin:/var/lib/mysql
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mysql
